stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - artifacts/raw/Images/
      - artifacts/raw/Labels/

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - artifacts/raw/Images/
      - artifacts/raw/Labels/
    outs:
      - artifacts/models/fasterrcnn.pth
